### ISSUE TITLE
Not working on OS X 10.10.5 (14F1021) with Sonic Pi 2.8

### ISSUE THREAD

**Issue by c5f** [fbehrens/sublime_sonic_pi#2]
No idea if you are maintaining this project, but I'd love to contribute by troubleshooting on the current Yosemite/Sonic Pi builds.

**Comment by fbehrens** [comment]
Sorry, saw this issue just now. Contributing will be possible, just send a pull request. I will soon check if the plugin works for SonicPi 2.8 on ElCapitain

**Comment by fbehrens** [comment]
I just update the readme to confirm  that 2.8 is working on El Capitain
